blank_issues_enabled: true
contact_links:
  - name: Privacy Policy
    url: https://github.com/agentical-info/android-homescreen-countdown/blob/main/PRIVACY_POLICY.md
    about: View our privacy policy and data collection practices
